<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{7a32f106-3942-4996-95db-32d556c79356}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	testBit				:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[testBit := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>